### ISSUE TITLE
[BUG] Need to login everytime to my HA over Wallpanel (NSPanel Pro) 

### ISSUE THREAD

**Issue by uros76** [TheTimeWalker/wallpanel-android#100]
**Describe the bug:**
When I login to my local Homeassistant server with Wallpanel installed on my NSPanel Pro everything works ok. But when I reboot the NSPanel Pro I need to login to HA again, everytime. I have three NSPanel Pro's and all of them do exactly same. 
I have updated the webkit and the wallpanel app. Still same problem. "Keep me logged in" is checked everyime I login in. 

Here are details from HA log after the NSPanel Pro reboots: 
```
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:80
Integration: HTTP ([documentation](https://www.home-assistant.io/integrations/http), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+http%22))
First occurred: October 1, 2023 at 05:55:01 (4 occurrences)
Last logged: 06:54:01

Login attempt or request with invalid authentication from 192.168.1.211 (192.168.1.211). Requested URL: '/api/websocket'. (Mozilla/5.0 (Linux; Android 8.1.0; px30_evb Build/OPM8.190605.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36)
```

**To Reproduce**
Steps to reproduce the behavior: Reboot NSPanel Pro 

**Smartphone-device (please complete the following information):**
 - Device: NSPanel Pro
 - OS: Android 8.01
 - Application: WallPanelApp-prod-universal-v0.11.0.apk

**Comment by TheTimeWalker** [comment]
Have you checked "Keep me logged in" on Home Assistant Login?

**Comment by Fredrik81** [comment]
I have similar issue. Using Lenovo tablet and I login with the "keep me logged in" checkbox. 
Feels like random but it logges me out and I see the login page when walking past the tablet. 
I have the refresh on wakeup checkbox enabled in settings.

**Comment by 877dev** [comment]
@uros76 same issue here although not everytime I reboot it, more like every 5th time.

Did you get any further on to a solution?

**Comment by uros76** [comment]
> @uros76 same issue here although not everytime I reboot it, more like every 5th time.
> 
> Did you get any further on to a solution?

I installed the com.android.webview_108.0.5359.128-535912803.apk and an updated WallPanelApp-prod-universal-v0.12.0.apk 
Since then HA dashboard over wallpanel app remembers the login and everything works.
