### ISSUE TITLE
[BUG] Can't get SSL/TLS connection working

### ISSUE THREAD

**Issue by aqwserf** [TheTimeWalker/wallpanel-android#102]
**Describe the bug**
I have a Mosquito broker with self-signed certificate and even with the `SSL/TLS Connection` activated and port set to 8883, I cannot get a working connection, the broker is resetting the connection. I've also tried with `mqtts://` but it doesn't work.
Am I misunderstanding this [wiki page](https://wallpanel.xyz/docs/remote-control/mqtt-setup/)? 
Is wallpanel support SSL/TLS connection to the broker with a self-signed certificate and if so, how? And what is the purpose of `SSL/TLS Connection`? According to the description, it's supposed to listen (??) to 8883 but I don't get it.

Besides that, the regular connection to port 1883 works fine, even with `SSL/TLS Connection` activated (which confuses me).

Thanks!

**To Reproduce**
* set the ip for the broker
* activate `SSL/TLS Connection`
* set port to `8883`

**Smartphone (please complete the following information):**
 - Device: Google Nexus 7
 - OS: LineageOS 18.1
 - Applicaiton version v0.12.0

**Comment by tboby** [comment]
@aqwserf Did you get this to work in the end? I'm facing a similar situation: no combination of settings results in it actually trying to connect using tls, even with a real certificate. Weirdly, it doesn't even show the error message saying the MQTT config is wrong.
