### ISSUE TITLE
[FEATURE] availability for fdroid store

### ISSUE THREAD

**Issue by Xyz00777** [TheTimeWalker/wallpanel-android#117]
**Your feature request. Please describe.**
Please also upload the application trough fdroid so users are not limited to devices with google play store. Fdroid is one of the best alternatives and it would be really nice if it would be also there.

**Comment by Xyz00777** [comment]
and even when you are not want to do it, its really nice that you and others have decided to develop these app further ^^

**Comment by TheTimeWalker** [comment]
Thanks for the interest! I will close this as a duplicate as we're tracking this already under #14
