### ISSUE TITLE
[FEATURE]Select internet browser

### ISSUE THREAD

**Issue by marcoahp** [TheTimeWalker/wallpanel-android#118]
**Your feature request. Please describe.**
What is the feature, why is it valuable to the community or application?
Allow select which internet browser use. I have an old table with android browser that do not support Home Asssitant, I have chrome browser too, but wallpanel use old browser and fail. All old tablets would need to solve it.

**NOTE**
We get many feature requests, each feature requires community support and also development time. Features that have no community support are not considered.   If you are not contributing to the feature, then the feature may not happen.

**Comment by TheTimeWalker** [comment]
Sorry, unfortunately this is not possible. WallPanel specifically uses Android's WebView and this will always use the default configured WebView from your Android system. If you want to have it use a different browser, you'd have to find a way to install a different WebView version as a system app.

**Comment by albertdb** [comment]
@TheTimeWalker Some phones ship with vendor signed Android System Webview and no other Webview defined (see below), so you can't neither update system one nor install Google one nor use Chrome one. I'm facing this exact situation, with a non-rootable phone, so there are zero alternative options apart from using a specific Webview component from WallPanel app, either Google's `com.google.android.webview` or Bromite's `org.bromite.webview`.

It would be awesome if you can generate a build that uses either one. It would give a second (wallpanel'ed) life to many devices. 

Thanks!

```
>aapt d xmltree framework-res.apk res/xml/config_webview_packages.xml
E: webviewproviders (line=17)
  E: webviewprovider (line=19)
    A: availableByDefault=(type 0x12)0xffffffff
    A: description="Android WebView" (Raw: "Android WebView")
    A: packageName="com.android.webview" (Raw: "com.android.webview")
```
