### ISSUE TITLE
How to migrate from earlier version?

### ISSUE THREAD

**Issue by TheVeryFirstLAD** [TheTimeWalker/wallpanel-android#12]
I have been using WallPanel for a year or so and love it.  How do I migrate from the old version to this one?

**Comment by TheTimeWalker** [comment]
As has been mentioned in the release notes, you have to install and reconfigure everything again. There is unfortunately no way to make an in-place upgrade as I had to create new signing keys for this and thus had to use a new application ID.

**Comment by supp0815** [comment]
Does the app has a new name? I can't find it in the Google Store.

**Comment by TheTimeWalker** [comment]
It's not on the Play Store yet: #4 

Closing this as the original question has been answered
