### ISSUE TITLE
Clock screensaver not exclusive

### ISSUE THREAD

**Issue by brjhaverkamp** [TheTimeWalker/wallpanel-android#121]
**Describe the bug**
There are 4 choices of screensaver at the moment: Clock, Dim, Wallpaper and Web. 
Between the last 3: Dim, Wallpaper and Web, the choice is mutually exclusive. If I choose web, wallpaper gets deselected, etc.
However, Clock can be chosen in combination with one of the other, it is not deselected if I actived e.g. web or wallpaper.
Is this intended behaviour? Or is this a bug

**To Reproduce**
Activate clock screensaver.
Activate dim screensaver
Activate web screensaver
Activate wallpanel screensaver

When dim screensaver is activated, the clock screensaver is not deactivated.
When web screensaver is activated, the dim screensaver is deactivated, but, again, the clock screensaver is not deactivated.
When wallpanel screensaver is activated, the web screensaver is deactivated, but, again, the clock screensaver is not deactivated.

**Smartphone (please complete the following information):**
 - Device: Lenovo TAB M4 tablet
 - OS: Android 8.1
 - Application version:0.12 build 0

**Comment by pardofelis** [comment]
Hi @brjhaverkamp, what you call a bug, I would call a feature. In fact, I like having the unsplash wallpaper background with an added clock in front of the image. 
I don't know whether this was intended in the first place, but I wouldn't change this behaviour.

**Comment by brjhaverkamp** [comment]
Hi pardofelis, 

I think you are right and this is a feature. I was thrown off by the select buttons between them, but an option to add a clock to any of the other screensaver effects makes sense :-)

**Comment by brjhaverkamp** [comment]
I think this can be closed
