### ISSUE TITLE
JS not working properly [BUG]

### ISSUE THREAD

**Issue by Vitt8matic** [TheTimeWalker/wallpanel-android#130]
**Describe the bug**
When I put in my home assistant IP, I can't see the login spaces to put username and password. I think JS related?

**To Reproduce**
I simply installed the app from the play store, inserted the IP and it doesn't work. Also tried apk from github and the oldest available version.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab E (SM-T560)
 - OS: Android 7 Custom ROM (DotOS)
 - Application version: 0.10.0; 0.12.0.

![Screenshot_20240428-205135](https://github.com/TheTimeWalker/wallpanel-android/assets/66425988/8a78fd8a-4e5a-4416-904f-74e1f8d0e86f)

**Comment by TheTimeWalker** [comment]
You need to update Android WebView on your device

**Comment by Vitt8matic** [comment]
> You need to update Android WebView on your device

Did it, still blank page with no login screen

**Comment by markmghali** [comment]
> > You need to update Android WebView on your device
> 
> Did it, still blank page with no login screen

how did you update your android webview? I am having the same issues on my asus tf700 custom rom android 7.1

**Comment by Vitt8matic** [comment]
I tried both the play store and an apk, both led to nothing
