### ISSUE TITLE
[FEATURE] Use Intent to call external screensaver app

### ISSUE THREAD

**Issue by theothernt** [TheTimeWalker/wallpanel-android#137]
**Your feature request. Please describe.**
Currently, you can set a different webpage URL as the screensaver after a timeout.

I already have a 3rd party screensaver app I'd like to call. I would like a setting to specify an activity to call instead of a URL, for example...

`com.neilturner.aerialviews/.ui.screensaver.TestActivity`

I would be happy to create a PR for this feature if it sounds like a good idea?

**Comment by sorryusernameisalreadytaken** [comment]
There is a intent open feature, did you know that. It that not what you need?

**Can you try this cmd with mqtt:**
{"url": "intent:#Intent;launchFlags=0x10000000;component=com.neilturner.aerialviews/.ui.screensaver.DreamActivity;end"}

**Comment by theothernt** [comment]
Thanks, I'll give that a try!

**Comment by sorryusernameisalreadytaken** [comment]
I would love to know if that works

**Comment by theothernt** [comment]
> I would love to know if that works

Will do. I had a question back in June from someone who is using Wallpanel and trying to get Aerial Views to work with it.

They appear to be using an Android tablet and with Wallpanel as a Home Assistant dashboard. 

Just looking back at the issue, they wanted the screensaver to start after x minutes - I'm not sure a remote MQTT command would help here. I was thinking that Wallpanel would invoke an Intent locally to start the screensaver?
