### ISSUE TITLE
[BUG] wakeTime doesn't seem to work MQTT

### ISSUE THREAD

**Issue by tclayson** [TheTimeWalker/wallpanel-android#148]
**Describe the bug**
When using the MQTT API you can send the `wake` command with the property `wakeTime`. According to the documentation this should wake the tablet from it's screensaver (clock, in my case) for the time specified (in seconds).

```
{
  "wake": true,
  "wakeTime": 10
}
```

However this doesn't seem to work. The tablet does wake up, but will sleep (return to the screensaver) after the settings-configured idle time, rather than the time sent in the `wakeTime` property.

This means it's not possible to wake the tablet for a short amount of time.

The expected behaviour is that the tablet should wake and should stay awake for the number of seconds that was sent in the `wakeTime` property in the JSON sent via MQTT.

**To Reproduce**
1. Set up Wallpanel with MQTT
2. Send an MQTT message to `[your]/[topic]/command` with the message `{ "wake": true, "wakeTime": 10 }`
3. Observe that the tablet wakes but stays awake for the time configured in the settings, rather than the `wakeTime` value

**Smartphone (please complete the following information):**
 - Device: Android Fire 8 (10th Generation)
 - OS: Fire OS
 - Applicaiton version: Latest

**Comment by tclayson** [comment]
Figured out that the `wakeTime` is _additional_ to the configured screensaver time. So by sending a value of 10s, and having the screensaver time configured to 1 min the screen will stay on for 1min 10s. So, there is no way to use `wakeTime` to turn the screen on for a time _less_ than the current configured screensaver time.

**Comment by sorryusernameisalreadytaken** [comment]
> Figured out that the `wakeTime` is _additional_ to the configured screensaver time. So by sending a value of 10s, and having the screensaver time configured to 1 min the screen will stay on for 1min 10s. So, there is no way to use `wakeTime` to turn the screen on for a time _less_ than the current configured screensaver time.

That make sense. Thx for clarify this
