### ISSUE TITLE
[FEATURE] A forum to discuss experience with Wallpanel and share information

### ISSUE THREAD

**Issue by brjhaverkamp** [TheTimeWalker/wallpanel-android#24]
**Your feature request. Please describe.**
Thanksmister had a forum dedicated to wallpanel, which was really good to share experience and find information about setups on different tables. Is it possible to set up something similar?
That would possibly also reduce the load on bug reports, if bugs first need to be discussed in the forum. ( A policy I learned in the freecad community)

Regards,

Bert Haverkamp

**Comment by zhimsel** [comment]
The "Discussions" feature in Github may be a reasonable solution to this.

**Comment by TheTimeWalker** [comment]
I thought about this but disabled it for now because I thought there wasn't enough traction to have this feature yet! I can reconsider this if more people need a place to discuss :)

**Comment by zhimsel** [comment]
Why not just enable it? If nobody uses it, then 🤷. But if anyone wants to,
it's there!

**Comment by brjhaverkamp** [comment]
From my side, please enable it. Likely it could even draw some more users to the app. And it will be a good place for existing users to help eachother. That could reduce the load on you.

**Comment by TheTimeWalker** [comment]
Discussions has been enabled! Feel free to discuss anything Wallpanel there!
https://github.com/TheTimeWalker/wallpanel-android/discussions
