### ISSUE TITLE
Is IP of DNS server hardcoded in wallpanel app?

### ISSUE THREAD

**Issue by bazylewicz** [TheTimeWalker/wallpanel-android#25]
I can't get my local (*.lan) domain to work with Wallpanel - always getting ERR_NAME_NOT_RESOLVED error.
The IP of local DNS server is configured in Wifi settings and on Android itself (Chrome etc) everything works fine.

Is it possible that DNS server IPs are hardcoded in app?
Using newest 10.0.1 version of Wallpanel.

**Comment by TheTimeWalker** [comment]
The app isn't setting any DNS config and the view itself is just a WebView which should use the internally installed WebView app on the system

**Comment by TheTimeWalker** [comment]
Closing as solved
