### ISSUE TITLE
[FEATURE] URL command - navigate using JS without reloading

### ISSUE THREAD

**Issue by luzik** [TheTimeWalker/wallpanel-android#26]
It would be awesome to have ability to switch Lovelace cards using builtin JS navigation.

My personal use case is that I have a card with 'open door' button and webrtc stream from my door cam that support background streaming. When someone press doorbell I want to switch/navigate to that card, but with navigation implemented in wallpanel (url command) I can only go there with reloading stream - that takes few seconds to show stream.
Switching card by touching Lovelace UI card navigates smooth and stream is shown instant. Switching card by navigating by wallpanel make it realod.

Maybe there is simple way using eval command ?

**Comment by TheTimeWalker** [comment]
As far as I know, there's no native way to do that. Pushing the state via history does not automatically navigate and there's no way to just do a "navigate" with the HA core.

I'd suggest to use something like [Browser Mod](https://github.com/thomasloven/hass-browser_mod) and instead automate with this. That's how I have personally solved this.

**Comment by JavanXD** [comment]
I tried to do this using something like:
```
curl --location --request POST 'http://192.168.178.78:2971/api/command' \
--header 'Content-Type: application/json;charset=UTF-8' \
--data-raw '{
    "eval": "document.querySelector("paper-tab[aria-label="Hauseingang"]").dispatchEvent(new MouseEvent("click", {shiftKey: true}));"                        
}';
```

According to the documentation the eval() is executed in the context of the dashboard, which means we should have access there and send javascript events.

Use Case: sending an `url` takes much time to reload the page, a simple javascript event, would be very fast in navigating on the dashboard.

For example I have one tab on my WallPanel showing the cameras, as soon someone rings my doorbell, or as soon as movement is detected by my camera, I want to trigger a wakeup event on the WallPanel as well as open the Camera sub-page. 

@TheTimeWalker could you have a look please why we are not able to execute / simulate Click Events on the Dashboard, is the DOM of the HA Dashboard not available or why? If we trigger alerts we should be able to access the dom, too?
