### ISSUE TITLE
Copy wiki from old repo

### ISSUE THREAD

**Issue by Daniel15** [TheTimeWalker/wallpanel-android#3]
Please copy the wiki from the old repo; it's very useful. Either that or get the wallpanel.app domain from the old maintainer and put all the content there.

https://github.com/thecowan/wallpanel-android/wiki

In particular, the MQTT commands aren't documented anywhere else: https://github.com/thecowan/wallpanel-android/wiki/MQTT-and-HTTP-Commands

**Comment by TheTimeWalker** [comment]
Yes! This is already planned. I wanted to actually go one step further and create a new documentation repo which generates a static documentation site. This should make it easier to create PRs for any changes as the Github Wiki unfortunately is very unflexible for collaboration.

**Comment by Daniel15** [comment]
> documentation repo which generates a static documentation site. 

[Docusaurus](https://docusaurus.io/) is fantastic for this use case.

You could keep the site in a `docs` folder in this repo rather than a separate repo, if you'd like to. Personally I like the combined app + docs repo since I can submit both a new feature **and** documentation for it in a single PR :)
