### ISSUE TITLE
[BUG] - Freezes Crashes/Freezes on Samsung A7, PinCode crashes on Huawei M5

### ISSUE THREAD

**Issue by TheQue42** [TheTimeWalker/wallpanel-android#37]
**Describe the bug**
Been waiting for the google play version, but could help myself today, so I installed the 0.10.1 directly from github.
My huawei mediapad M5 had some issues starting, but eventually it seems to work fairly well, except when I try to click to set the pin code. The app just terminates/vanishes/crashes.
Every single time.

However, on my samsung A7 tablet, the app completely freezes.

**To Reproduce**
(Try to) start the app on Samsung A7....:-( 
Killing the app, and holding the app-icon makes it possible to enter the configuration page, but changing to my local home-assistant page doesnt help anything. (While the real homeassistant app works fine on the tablet, as well as the old "original" wallpanel app.
Entering the config-page, and pressing the "pin-code" setting to change it, will terminate/crash the app. Also tried killing app and removing all storage, but to no avail.

**Smartphone (please complete the following information):**
 - Standard Samsung Tab A7, SM-T500.
 - Android v12

Not much to go on I know, but feel free to tell me how to find more bug-info for troubleshooting.

**Comment by TheTimeWalker** [comment]
I can't comment on the pin code crash on M5 yet since I couldn't recreate this.

Samsung A7 please try with the v0.10.2 version [from the releases section](https://github.com/TheTimeWalker/wallpanel-android/releases/tag/v0.10.2)

**Comment by dexonter** [comment]
Pin code crash happening on Fire HD 8 Plus (10th Gen) as well

**Comment by TheQue42** [comment]
> I can't comment on the pin code crash on M5 yet since I couldn't recreate this.
> 
> Samsung A7 please try with the v0.10.2 version [from the releases section](https://github.com/TheTimeWalker/wallpanel-android/releases/tag/v0.10.2)

Oh, just superb! Solved the freeze/crash on my A7!! Thanks a million for this quick fix. The pincode crash still around, on both devices.

**Comment by bazylewicz** [comment]
Yesterday I updated my Samsung Galaxy Tab A8 to Android v12, and there is a blank screen after trying to run Wallpanel (it freezes). Updating Wallpanel to 0.10.2 didnt help. What could be wrong?

**Comment by TheTimeWalker** [comment]
@bazylewicz Sounds like #22

**Comment by TheTimeWalker** [comment]
Closing as both issues with freezing and pin code crashing have been fixed since v0.10.5
