### ISSUE TITLE
[BUG] Pulish app on the google play store

### ISSUE THREAD

**Issue by starkillerOG** [TheTimeWalker/wallpanel-android#4]
Could you pubilish this application again on the google play store using this new repositry?
Link to the issue in the old repositry: https://github.com/thecowan/wallpanel-android/issues/324

**Comment by starkillerOG** [comment]
@TheTimeWalker Thank you so much for picking up the maintenance of this greath application.
Much appriciated!

**Comment by TheTimeWalker** [comment]
I don't know how to continue with this yet as I don't have access to the original Play Store listing and I think @thanksmister doesn't have access anymore either. In this case, I would have to create a new app with a new app ID, which would mean that anybody currently using the app must reinstall the app and remove their old one. There is no upgrade path.

**Comment by thanksmister** [comment]
Yea we lost access to the old play store listing along with the repository.  You would need a new app ID and change the package path so it doesn’t conflict with existing path in play store.   You also need a new app signing certificate.

**Comment by starkillerOG** [comment]
@TheTimeWalker @thanksmister could we contact Google and ask to restore the acount owner to the original (tanksmister) and then transfer it to TheTimeWalker?
Google schould also be able to see that the current app is dead and unavailable and schould be able to see in the history that tanksmister was the original owner and coud for instance give the current owner a few weeks to respond and otherwise transfer ownership back to tanksmister?

Or is this not possible?

**Comment by ptv1p3r** [comment]
New user here, so where can i find the new app in google play ?

**Comment by starkillerOG** [comment]
@TheTimeWalker any updates regarding creating a new app with a new app ID for the google play store?

**Comment by TheTimeWalker** [comment]
I never published an app as a private entity which means that there are a few lengthy processes to do on Google Play Store before the app is published.

**Comment by nighi** [comment]
Maybe it's a good time to think about releasing the app to the f-droid store as well. That could also attract possible contributes.

**Comment by brjhaverkamp** [comment]
Hello,
Is there any progress on the playstore publishing?
I would love to update to a new, stable release. The last one on github is [v0.10.0-beta1](https://github.com/TheTimeWalker/wallpanel-android/releases/tag/v0.10.0.1)
Is that a recommended update?

**Comment by TheTimeWalker** [comment]
This is currently the latest version, yes. You can use that to download and run for now as it's the same signing keys that will be used for Play Store.

**Comment by svenstaro** [comment]
You should remove the Google app store link in the readme in the meantime because currently it's a bit confusing for users.

**Comment by AzureAzim** [comment]
Big fan of this app! Thanks for Picking it back up @TheTimeWalker  and @thanksmister 

I think i would be OK with there just being a new app in the play store. Having it deployed via play store is critical to the automations i have built on getting these devices set up (using Intune managed device profiles to automate half the setup)

Happy to donate in order to cover your Google Play Developer fees to get this moved forward!

**Comment by svenstaro** [comment]
The play store link is still prominent in the README and it's still not available in play store. Just get a new account and re-publish the app there.

**Comment by TheTimeWalker** [comment]
Yes, sorry for the delay! I planed to do this earlier but didn't come around to prepping it up. Let me check and merge the PR which should fix the MQTT loop bug and publish a new version which would be used for the Play Store release

**Comment by TheTimeWalker** [comment]
Just as a small update, the app has been sent to Google Play and is currently under review. The link on the README should be the correct one as soon as the app gets approved.

**Comment by AzureAzim** [comment]
@TheTimeWalker i 100% do not feel like the donation was in vain, im just grateful you picked up this project and resurrected it! Fingers crossed on play store review! Thanks again!

**Comment by TheTimeWalker** [comment]
The app has been reviewed and is now available in Play Store!

Link: https://play.google.com/store/apps/details?id=xyz.wallpanel.app
