### ISSUE TITLE
[BUG] Intent URI not working

### ISSUE THREAD

**Issue by juanpintom** [TheTimeWalker/wallpanel-android#49]
**Describe the bug**
First of all, thank you very much for this insane app. Probably isn't a problem with Wallpanel App but I can't open Home Assistant app with intent configured on Dashboard URL, return Connection Error screen from HASS.

I want to load Home assistant App at start to use swipe function and other improvments instead using the webview of Hass (this works well) 

**To Reproduce**
Set Dashboard url on Wallpanel app: http://intent:#Intent;launchFlags=0x10000000;component=io.homeassistant.companion.android/io.homeassistant.companion.android.launch.LaunchActivity;end

Intent found with FKB and works well

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsun, Android, Fire Tablet] Samsung Galaxy Tab A Tablet
 - OS: [e.g. Android 21, Oreo, Fire OS 7] Android 7.1.1
 - Applicaiton version [app > settings > version] 0.9.5 Build 9

**Comment by Nespouique** [comment]
Hi, i have the same issue, i want to open Homey android app, works like a charm in Fully Kiosk but cant get it to work in Wallpanel :'(
