### ISSUE TITLE
[BUG] App Restart/Crash after PIN Code Change

### ISSUE THREAD

**Issue by n3roGit** [TheTimeWalker/wallpanel-android#52]
Hi, I just switched from the old repo to yours. Unfortunately I have the problem that the app crashes when I want to assign a code (security pin).
Currently I have tested this with version 10.2 and 10.4.
Used on a FireHD10

**Comment by n3roGit** [comment]
It may have something to do with it:

https://github.com/TheTimeWalker/wallpanel-android/issues/37

**Comment by Mikle61** [comment]
I have the same :-(. When I try to enter the pin code, the application crashes :-( I used to have version 0.9.7 - everything was OK

**Comment by n3roGit** [comment]
Please push the thumbs up Button to make this issue more visible

**Comment by starbyte007** [comment]
same problem
Android 10
with version 0.9.6 okay
with version 0.10.3 and 0.10.4 crash when creating pin code

**Comment by Roger-NL1975** [comment]
Same problem
New install on Lenovo tab 10

**Comment by Chacsam** [comment]
Same issue on Lenovo Tab 11, Android 12

**Comment by papinist** [comment]
Same issue on Huawei Mediapad M2, Android 5.1.1

**Comment by bgruszka** [comment]
Same issue here, Telcast M40 Pro, Android 11

**Comment by nagydavid** [comment]
Same issue in Samsung Galaxy Tab A7 Lite

**Comment by uyuarasy** [comment]
Same issue in Huawei Mediapad T3 10, Android 7.0, installed 0.10.3 Build 0 from Play Store.

**Comment by Karabacak021** [comment]
Same problem.
New install to:
Acer Iconia One 10 B3-A30 A6003
Android 6.0
Wallpanel 0.10.4
