### ISSUE TITLE
Presence detection in the dark

### ISSUE THREAD

**Issue by wnaude** [TheTimeWalker/wallpanel-android#69]
Hi, I just found your great app and is playing around with all the options. Not yet familiar with everything, so please let me know if I missed an existing option.

The motion detection can be great to turn on the screen and even a light when it is dark. The problem is that it is not working in the dark.

My suggestion to assist with this, is a presence detection with the following two triggers:
1. Screen touched
2. Sound/Voice detected

Your kind consideration will be appreciated.

**Comment by 86lava** [comment]
The app already can "wake" from screensaver mode when the screen is touched.
