### ISSUE TITLE
[BUG] cannot refesh page via location.reload() 

### ISSUE THREAD

**Issue by smcgann99** [TheTimeWalker/wallpanel-android#70]
I have tried to incorporate a refresh button in my web page, but nothing I have tried seems to work (with webview)
The same page works fine in chrome.

**To Reproduce**
add a button to the web page something like -
`<button onclick="location.reload()">refresh</button>`

2 different generic Android 10 Tablets.

**Comment by TheTimeWalker** [comment]
It's possible that location is not directly available in the WebView. Have you tried to use other solutions (e.g. window.location.reload()? There are a few examples here: https://stackoverflow.com/questions/29884654/button-that-refreshes-the-page-on-click#29884677

**Comment by smcgann99** [comment]
So I tried window.location.reload() but no luck.

**Comment by TheTimeWalker** [comment]
It looks like such events are thrown away because of [shouldOverrideLoading returning true](https://github.com/TheTimeWalker/wallpanel-android/blob/85c0efab4a4d172ac237b2e9e1d79eefa1d67f72/WallPanelApp/src/main/java/xyz/wallpanel/app/utils/InternalWebClient.kt#L34).

**Comment by smcgann99** [comment]
Indeed that looks like the case - but as there is no access to a browser refresh button, the abliity to do this from within the page is really needed ? 
I'm using it to display IOT dashboards from NODE-RED, and I cannot send a refresh from the server side either.
At the moment I'm having to use the wallpanel command topic to refresh via MQTT, but its not ideal.
