### ISSUE TITLE
[BUG] Breaking changes for MQTT in Home Assistant 2023.8

### ISSUE THREAD

**Issue by redneckdba** [TheTimeWalker/wallpanel-android#90]
**Describe the bug**
After upgrading my HomeAssistant to 2023.8 my logs are flooded regarding WallPanel MQTT entities due to a breaking change in HA.
From the Release Notes:

> The way MQTT entities are named and how device configuration can be shared between discovered entities has changed.

Sharing of device configuration

Discovered MQTT entities can share device configuration, meaning one entity can include the full device configuration, and other entities can link to that device by only setting mandatory fields.

The mandatory fields were previously limited to at least one of connection and identifiers, but have now been extended to at least one of connection and identifiers as well as the name.

Naming of MQTT entities

The naming of MQTT entities has been changed to be aligned with the [entity naming guidelines](https://developers.home-assistant.io/docs/core/entity/#entity-naming):

The has_entity_name entity will be set to True on all MQTT entities.
This means any MQTT entity which is part of a device will [automatically have its friendly_name attribute prefixed with the device name](https://developers.home-assistant.io/docs/core/entity/#has_entity_name-true-mandatory-for-new-integrations).
Unnamed binary_sensor, button, event, number, and sensor entities will now be named by their device class instead of being named “MQTT binary sensor” etc.
It’s now allowed to set an MQTT entity’s name to None to mark it as the main feature of a device.

[https://www.home-assistant.io/blog/2023/08/02/release-20238/](url)

**To Reproduce**
Upgrade Home Assistant to 2023.8 with WallPanel MQTT entities

**Smartphone (please complete the following information):**
 - Device: Samsung GalaxyTab A7 Lite
 - OS: Android 13
 - Application version: 0.10.15

**Comment by golds69** [comment]
I have the same problem since Home Assistant version 2023.8.0
Please fix MQTT Discovery for the new Home Assistant requirements.

**Comment by tmakowka** [comment]
I'm still on 2023.7, but reading this I'll wait until this is fixed in Wallpanel. 

Please fix this issue! 😀
